name: リリースノートPR作成

on:
  workflow_dispatch:

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "ibulog"
        git config user.email "ibulog76@gmail.com"
    
    - name: Set Today Day
      id: today_day
      continue-on-error: true
      run: echo "today_day=$(date +%u)" >> $GITHUB_OUTPUT

    - name: Set Branch Variable for Friday
      if: steps.today_day.outputs.today_day == 3
      run: |
        next_day_date=$(date '+%Y-%m-%d' --date '3 day')
        echo "next_day_date=${next_day_date}" >> $GITHUB_ENV
        branch_name="hanica_${next_day_date}"
        echo "branch_name=$branch_name" >> $GITHUB_ENV

    - name: Set Branch Variable
      if: steps.today_day.outputs.today_day != 3
      run: |
        next_day_date=$(date '+%Y-%m-%d' --date '1 day')
        echo "next_day_date=${next_day_date}" >> $GITHUB_ENV
        branch_name="hanica_${next_day_date}"
        echo "branch_name=$branch_name" >> $GITHUB_ENV
        
    - name: Create Branch
      run: |
        git switch -c ${branch_name}

    - name: Install Dependencies and Run Yarn
      run: |
        yarn install
        touch test
        git add .
        git commit -m "${branch_name}のリリースノート作成"
        git push origin ${branch_name}

    - name: Create Release Pull Request
      run: |
        gh pr create \
          -B master \
          -t "${branch_name}のリリースノート作成" \
          -F ./.github/PULL_REQUEST_TEMPLATE_RELEASE_NOTE.md \
          -a ${{ github.actor }}


