name: リリースノートPR作成

on:
  workflow_dispatch:

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Set up Git
      run: |
        git config user.name "ibulog"
        git config user.email "ibulog76@gmail.com"

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Branch
      run: |
        tomorrow=$(date '+%Y-%m-%d' --date '1 day')
        echo "tomorrow=${tomorrow}" >> $GITHUB_ENV
        branch_name="hanica_${tomorrow}"
        echo "branch_name=$branch_name" >> $GITHUB_ENV
        git switch -c ${branch_name}

    - name: Install Dependencies and Run Yarn
      run: |
        yarn install
        touch test
        git add .
        git commit -m "${branch_name}のリリースノート作成"
        git push origin ${branch_name}

    - name: Create Release Pull Request
      run: |
        gh pr create \
          -B master \
          -t "${branch_name}のリリースノート作成" \
          -F ./.github/PULL_REQUEST_TEMPLATE_RELEASE_NOTE.md \
          -a ${{ github.actor }}


