name: リリースノートPR作成

on:
  workflow_dispatch:

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Create Branch
      run: |
        tomorrow=$(date '+%Y-%m-%d' --date '1 day')
        echo "tomorrow=$tomorrow" >> $GITHUB_ENV
        branch_name="hanica_$today"
        echo "branch_name=$branch_name" >> $GITHUB_ENV
        git switch -c $branch_name

    - name: Install Dependencies and Run Yarn
      run: |
        yarn install
        touch test
        git add .
        git commit -m "$branch_nameのリリースノート作成"
        git push origin $branch_name

    - name: Create Release Pull Request
      if: ${{ steps.check_pr.outputs.count == 0 }}
      run: |
        gh pr create \
          -B master \
          -t "$branch_nameのリリースノート作成" \
          -a ${{ github.actor }}  \


